In [40]:
import pandas as pd

In [41]:
iris=pd.read_csv('iris.csv')

In [42]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [43]:
iris[iris['sepal.width']>4]

    sepal.length  sepal.width  petal.length  petal.width variety
15           5.7          4.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa

In [44]:
iris[iris['petal.width']>1]

     sepal.length  sepal.width  petal.length  petal.width     variety
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   Virginica
146           6.3          2.5           5.0          1.9   Virginica
147           6.5          3.0           5.2          2.0   Virginica
148           6.2          3.4           5.4          2.3   Virginica
149           5.9          3.0           5.1          1.8   Virginica

[93 rows x 5 columns]

In [45]:
iris[iris['petal.width']>2]

     sepal.length  sepal.width  petal.length  petal.width    variety
100           6.3          3.3           6.0          2.5  Virginica
102           7.1          3.0           5.9          2.1  Virginica
104           6.5          3.0           5.8          2.2  Virginica
105           7.6          3.0           6.6          2.1  Virginica
109           7.2          3.6           6.1          2.5  Virginica
112           6.8          3.0           5.5          2.1  Virginica
114           5.8          2.8           5.1          2.4  Virginica
115           6.4          3.2           5.3          2.3  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica
120           6.9          3.2           5.7          2.3  Virginica
124           6.7          3.3           5.7          2.1  Virginica
128           6.4          2.8           5.6          2.1  Virginica
132           6.4          2.8           5.6          2.2  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
148           6.2          3.4           5.4          2.3  Virginica

In [46]:
y=iris[['sepal.length']]

In [47]:
x=iris[['sepal.width','petal.length']]

In [48]:
from sklearn.model_selection import train_test_split;

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [50]:
x_train.head()

     sepal.width  petal.length
9            3.1           1.5
133          2.8           5.1
141          3.1           5.1
140          3.1           5.6
45           3.0           1.4

In [51]:
x_test.head()

     sepal.width  petal.length
66           3.0           4.5
138          3.0           4.8
27           3.5           1.5
93           2.3           3.3
84           3.0           4.5

In [52]:
y_train.head()

     sepal.length
9             4.9
133           6.3
141           6.9
140           6.7
45            4.8

In [53]:
y_test.head()

     sepal.length
66            5.6
138           6.0
27            5.2
93            5.0
84            5.4

In [54]:
#categorize the data was done till here as train and test data

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
lr=LinearRegression()

In [57]:
lr.fit(x_train,y_train)

LinearRegression()

In [58]:
y_pred=lr.predict(x_test)

In [59]:
y_test.head()
#actual value

     sepal.length
66            5.6
138           6.0
27            5.2
93            5.0
84            5.4

In [60]:
y_pred[0:5]
#predicted value

array([[6.17251753],
       [6.31334815],
       [5.04374297],
       [5.21785076],
       [6.17251753]])

In [61]:
#we find out the error in prediction
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

0.11754920595342445

# model 2

In [62]:
#using 3 independent values

In [63]:
y=iris[['sepal.length']]

In [64]:
x=iris[['sepal.width','petal.width']]

In [65]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [66]:
lr2=LinearRegression()

In [67]:
lr2.fit(x_train,y_train)

LinearRegression()

In [68]:
y_pred=lr2.predict(x_test)

In [69]:
y_test.head()

     sepal.length
115           6.4
85            6.0
15            5.7
32            5.2
5             5.4

In [70]:
y_pred[0:5]

array([[7.04408343],
       [6.41551789],
       [5.61756435],
       [5.18407347],
       [5.40483481]])

In [71]:
mean_squared_error(y_test,y_pred)

0.17942057744469267

# model 3

In [72]:
y=iris[['sepal.length']]

In [73]:
x=iris[['petal.length','petal.width']]

In [74]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [75]:
lr3=LinearRegression()

In [76]:
lr3.fit(x_train,y_train)

LinearRegression()

In [77]:
y_pred=lr3.predict(x_test)

In [78]:
y_test.head()

    sepal.length
37           4.9
81           5.5
32           5.2
88           5.6
20           5.4

In [79]:
y_pred[0:5]

array([[4.85383615],
       [5.83937991],
       [4.90770345],
       [5.97038104],
       [4.98728203]])

In [80]:
mean_squared_error(y_test,y_pred)

0.21969215145134882

# model 4

In [81]:
y=iris[['petal.length']]

In [82]:
x=iris[['sepal.length','petal.length','petal.width']]

In [83]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [84]:
lr4=LinearRegression()

In [87]:
lr4.fit(x_train,y_train)

LinearRegression()

In [88]:
y_pred=lr4.predict(x_test)

In [89]:
y_test.head()
y_pred[0:5]

array([[1.7],
       [5.8],
       [1.3],
       [4.7],
       [1.7]])

In [90]:
mean_squared_error(y_test,y_pred)

1.169048035931694e-30

# model 5

In [122]:
y = iris[['sepal.width']]

In [123]:
x = iris[['sepal.length','petal.length','petal.width']]

In [124]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [125]:
lr5=LinearRegression()
lr5.fit(x_train,y_train)
y_pred=lr5.predict(x_test)
y_test.head()
mean_squared_error(y_test,y_pred)

0.10002515686394756

# model 6

In [127]:
y = iris[['sepal.width']]

In [128]:
x = iris[['petal.length','petal.width']]

In [129]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [130]:
lr6=LinearRegression()
lr6.fit(x_train,y_train)

LinearRegression()

In [131]:
y_pred=lr6.predict(x_test)
y_test.head()

     sepal.width
9            3.1
44           3.8
124          3.3
65           3.1
74           2.9

In [132]:
mean_squared_error(y_test,y_pred)

0.14743157690949393